{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP00aAoBKLHbI2uL1TaS8T2",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MBR4V0/TESTE4/blob/main/Machine1.C\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "oK8pCbGRqeed"
      },
      "outputs": [],
      "source": [
        "#include <stdio.h>\n",
        "#include <stdlib.h>\n",
        "#include <math.h>\n",
        "#include <time.h>\n",
        "\n",
        "#define INPUT 2\n",
        "#define HIDDEN 4\n",
        "#define OUTPUT 1\n",
        "#define LR 0.5\n",
        "#define EPOCHS 10000\n",
        "\n",
        "// ativação sigmoid\n",
        "double sigmoid(double x) {\n",
        "    return 1.0 / (1.0 + exp(-x));\n",
        "}\n",
        "\n",
        "// derivada da sigmoid\n",
        "double dsigmoid(double x) {\n",
        "    return x * (1.0 - x);\n",
        "}\n",
        "\n",
        "// inicialização aleatória\n",
        "double rand_weight() {\n",
        "    return ((double)rand() / RAND_MAX) * 2 - 1;\n",
        "}\n",
        "\n",
        "int main() {\n",
        "    srand(time(NULL));\n",
        "\n",
        "    // dataset XOR\n",
        "    double X[4][INPUT] = {\n",
        "        {0,0},\n",
        "        {0,1},\n",
        "        {1,0},\n",
        "        {1,1}\n",
        "    };\n",
        "\n",
        "    double Y[4][OUTPUT] = {\n",
        "        {0},\n",
        "        {1},\n",
        "        {1},\n",
        "        {0}\n",
        "    };\n",
        "\n",
        "    // pesos\n",
        "    double w1[INPUT][HIDDEN];\n",
        "    double w2[HIDDEN][OUTPUT];\n",
        "\n",
        "    double b1[HIDDEN];\n",
        "    double b2[OUTPUT];\n",
        "\n",
        "    // inicializar pesos\n",
        "    for (int i = 0; i < INPUT; i++)\n",
        "        for (int j = 0; j < HIDDEN; j++)\n",
        "            w1[i][j] = rand_weight();\n",
        "\n",
        "    for (int i = 0; i < HIDDEN; i++)\n",
        "        for (int j = 0; j < OUTPUT; j++)\n",
        "            w2[i][j] = rand_weight();\n",
        "\n",
        "    for (int i = 0; i < HIDDEN; i++) b1[i] = rand_weight();\n",
        "    for (int i = 0; i < OUTPUT; i++) b2[i] = rand_weight();\n",
        "\n",
        "    // treinamento\n",
        "    for (int epoch = 0; epoch < EPOCHS; epoch++) {\n",
        "\n",
        "        for (int sample = 0; sample < 4; sample++) {\n",
        "\n",
        "            double hidden[HIDDEN];\n",
        "            double output[OUTPUT];\n",
        "\n",
        "            // forward hidden\n",
        "            for (int j = 0; j < HIDDEN; j++) {\n",
        "                hidden[j] = b1[j];\n",
        "                for (int i = 0; i < INPUT; i++) {\n",
        "                    hidden[j] += X[sample][i] * w1[i][j];\n",
        "                }\n",
        "                hidden[j] = sigmoid(hidden[j]);\n",
        "            }\n",
        "\n",
        "            // forward output\n",
        "            for (int j = 0; j < OUTPUT; j++) {\n",
        "                output[j] = b2[j];\n",
        "                for (int i = 0; i < HIDDEN; i++) {\n",
        "                    output[j] += hidden[i] * w2[i][j];\n",
        "                }\n",
        "                output[j] = sigmoid(output[j]);\n",
        "            }\n",
        "\n",
        "            // erro\n",
        "            double error = Y[sample][0] - output[0];\n",
        "\n",
        "            // backprop output\n",
        "            double delta_output = error * dsigmoid(output[0]);\n",
        "\n",
        "            double delta_hidden[HIDDEN];\n",
        "\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                delta_hidden[i] = dsigmoid(hidden[i]) * w2[i][0] * delta_output;\n",
        "            }\n",
        "\n",
        "            // atualizar pesos output\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                w2[i][0] += LR * delta_output * hidden[i];\n",
        "            }\n",
        "            b2[0] += LR * delta_output;\n",
        "\n",
        "            // atualizar pesos hidden\n",
        "            for (int i = 0; i < INPUT; i++) {\n",
        "                for (int j = 0; j < HIDDEN; j++) {\n",
        "                    w1[i][j] += LR * delta_hidden[j] * X[sample][i];\n",
        "                }\n",
        "            }\n",
        "\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                b1[i] += LR * delta_hidden[i];\n",
        "            }\n",
        "        }\n",
        "    }\n",
        "\n",
        "    // teste\n",
        "    printf(\"Resultados treinados (XOR):\\n\");\n",
        "    for (int sample = 0; sample < 4; sample++) {\n",
        "\n",
        "        double hidden[HIDDEN];\n",
        "        double output[OUTPUT];\n",
        "\n",
        "        for (int j = 0; j < HIDDEN; j++) {\n",
        "            hidden[j] = b1[j];\n",
        "            for (int i = 0; i < INPUT; i++) {\n",
        "                hidden[j] += X[sample][i] * w1[i][j];\n",
        "            }\n",
        "            hidden[j] = sigmoid(hidden[j]);\n",
        "        }\n",
        "\n",
        "        for (int j = 0; j < OUTPUT; j++) {\n",
        "            output[j] = b2[j];\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                output[j] += hidden[i] * w2[i][j];\n",
        "            }\n",
        "            output[j] = sigmoid(output[j]);\n",
        "        }\n",
        "\n",
        "        printf(\"%.0f XOR %.0f = %.4f\\n\",\n",
        "               X[sample][0], X[sample][1], output[0]);\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ]
    }
  ]
}