{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOnhRBDOYKwrakUFVaX9Het",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MBR4V0/Code_C/blob/main/Machine2.C\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "oK8pCbGRqeed"
      },
      "outputs": [],
      "source": [
        "#include <stdio.h>\n",
        "#include <stdlib.h>\n",
        "#include <math.h>\n",
        "#include <time.h>\n",
        "\n",
        "#define INPUT 2\n",
        "#define HIDDEN 2\n",
        "#define OUTPUT 1\n",
        "#define LR 0.5\n",
        "#define EPOCHS 10000\n",
        "\n",
        "// dataset XOR\n",
        "double X[4][INPUT] = {\n",
        "    {0,0},\n",
        "    {0,1},\n",
        "    {1,0},\n",
        "    {1,1}\n",
        "};\n",
        "\n",
        "double Y[4][OUTPUT] = {\n",
        "    {0},\n",
        "    {1},\n",
        "    {1},\n",
        "    {0}\n",
        "};\n",
        "\n",
        "// pesos e bias\n",
        "double w1[INPUT][HIDDEN];\n",
        "double w2[HIDDEN][OUTPUT];\n",
        "double b1[HIDDEN];\n",
        "double b2[OUTPUT];\n",
        "\n",
        "// ativação\n",
        "double sigmoid(double x) {\n",
        "    return 1.0 / (1.0 + exp(-x));\n",
        "}\n",
        "\n",
        "double dsigmoid(double x) {\n",
        "    return x * (1.0 - x);\n",
        "}\n",
        "\n",
        "// random init\n",
        "double randw() {\n",
        "    return ((double)rand() / RAND_MAX) * 2 - 1;\n",
        "}\n",
        "\n",
        "// forward\n",
        "void forward(double input[INPUT], double hidden[HIDDEN], double output[OUTPUT]) {\n",
        "\n",
        "    // hidden layer\n",
        "    for (int j = 0; j < HIDDEN; j++) {\n",
        "        hidden[j] = b1[j];\n",
        "        for (int i = 0; i < INPUT; i++) {\n",
        "            hidden[j] += input[i] * w1[i][j];\n",
        "        }\n",
        "        hidden[j] = sigmoid(hidden[j]);\n",
        "    }\n",
        "\n",
        "    // output layer\n",
        "    for (int j = 0; j < OUTPUT; j++) {\n",
        "        output[j] = b2[j];\n",
        "        for (int i = 0; i < HIDDEN; i++) {\n",
        "            output[j] += hidden[i] * w2[i][j];\n",
        "        }\n",
        "        output[j] = sigmoid(output[j]);\n",
        "    }\n",
        "}\n",
        "\n",
        "// treino (backprop)\n",
        "void train() {\n",
        "\n",
        "    double hidden[HIDDEN];\n",
        "    double output[OUTPUT];\n",
        "\n",
        "    for (int epoch = 0; epoch < EPOCHS; epoch++) {\n",
        "\n",
        "        double total_error = 0;\n",
        "\n",
        "        for (int s = 0; s < 4; s++) {\n",
        "\n",
        "            forward(X[s], hidden, output);\n",
        "\n",
        "            // erro\n",
        "            double error = Y[s][0] - output[0];\n",
        "            total_error += error * error;\n",
        "\n",
        "            // delta output\n",
        "            double delta_out = error * dsigmoid(output[0]);\n",
        "\n",
        "            // delta hidden\n",
        "            double delta_hidden[HIDDEN];\n",
        "\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                delta_hidden[i] = dsigmoid(hidden[i]) * w2[i][0] * delta_out;\n",
        "            }\n",
        "\n",
        "            // atualizar pesos output\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                w2[i][0] += LR * delta_out * hidden[i];\n",
        "            }\n",
        "            b2[0] += LR * delta_out;\n",
        "\n",
        "            // atualizar pesos hidden\n",
        "            for (int i = 0; i < INPUT; i++) {\n",
        "                for (int j = 0; j < HIDDEN; j++) {\n",
        "                    w1[i][j] += LR * delta_hidden[j] * X[s][i];\n",
        "                }\n",
        "            }\n",
        "\n",
        "            for (int i = 0; i < HIDDEN; i++) {\n",
        "                b1[i] += LR * delta_hidden[i];\n",
        "            }\n",
        "        }\n",
        "\n",
        "        if (epoch % 1000 == 0) {\n",
        "            printf(\"Epoch %d | Error: %.6f\\n\", epoch, total_error);\n",
        "        }\n",
        "    }\n",
        "}\n",
        "\n",
        "int main() {\n",
        "\n",
        "    srand(time(NULL));\n",
        "\n",
        "    // inicialização dos pesos\n",
        "    for (int i = 0; i < INPUT; i++)\n",
        "        for (int j = 0; j < HIDDEN; j++)\n",
        "            w1[i][j] = randw();\n",
        "\n",
        "    for (int i = 0; i < HIDDEN; i++)\n",
        "        for (int j = 0; j < OUTPUT; j++)\n",
        "            w2[i][j] = randw();\n",
        "\n",
        "    for (int i = 0; i < HIDDEN; i++) b1[i] = randw();\n",
        "    for (int i = 0; i < OUTPUT; i++) b2[i] = randw();\n",
        "\n",
        "    train();\n",
        "\n",
        "    // teste final\n",
        "    printf(\"\\nResultados XOR:\\n\");\n",
        "\n",
        "    double hidden[HIDDEN];\n",
        "    double output[OUTPUT];\n",
        "\n",
        "    for (int i = 0; i < 4; i++) {\n",
        "        forward(X[i], hidden, output);\n",
        "        printf(\"%.0f XOR %.0f = %.4f\\n\",\n",
        "               X[i][0], X[i][1], output[0]);\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ]
    }
  ]
}